"""WhatsApp orchestration: verify, parse, dedup, converse, reply.

This ties the pieces together but stays intentionally thin. Phase A2 introduced
dedup + a static echo reply. Phase A3 routed each inbound message through the
:class:`ConversationManager` so replies are aware of session state. Phase A4
plugs in the LLM :class:`~app.llm.orchestrator.Orchestrator`: when wired, the
reply is generated by the model + tool-calling loop instead of the static
per-state copy. Phase A9 adds analytics event emission. The webhook,
idempotency, and session plumbing stay the same.

No domain logic lives here: prices/stock/totals always come from the backend
(BR-004), via the orchestrator's tools.
"""

from __future__ import annotations

from app.analytics.emitter import NullAnalyticsEmitter
from app.analytics.events import AnalyticsEventType
from app.config import Settings
from app.conversation.manager import HANDOVER_REASON_KEY, ConversationManager
from app.conversation.models import ConversationState, Session
from app.llm.orchestrator import Orchestrator
from app.platform.logging import get_logger
from app.safety.handover import HandoverReason, acknowledgement
from app.safety.injection import REFUSAL_REPLY, is_injection_attempt
from app.whatsapp.idempotency import InboundDedup
from app.whatsapp.models import InboundMessage, OutboundMessage
from app.whatsapp.outbound import OutboundSender
from app.whatsapp.provider import WhatsAppProvider

logger = get_logger(__name__)

# Context flag marking that the one-time handover acknowledgement was already
# sent, so we don't repeat it on every subsequent message while handed over.
_HANDOVER_ACKED_KEY = "handover_acked"



class WhatsAppService:
    """Coordinates inbound handling, conversation state, and outbound replies."""

    def __init__(
        self,
        *,
        settings: Settings,
        provider: WhatsAppProvider,
        dedup: InboundDedup,
        sender: OutboundSender,
        conversations: ConversationManager | None = None,
        orchestrator: Orchestrator | None = None,
        analytics=None,
    ):
        self._settings = settings
        self._provider = provider
        self._dedup = dedup
        self._sender = sender
        self._conversations = conversations
        self._orchestrator = orchestrator
        self._analytics = analytics if analytics is not None else NullAnalyticsEmitter()

    @property
    def provider(self) -> WhatsAppProvider:
        """The underlying provider (used by the webhook for verify/parse)."""
        return self._provider

    async def handle_inbound(self, message: InboundMessage) -> None:
        """Process a single inbound message: dedup, advance state, then reply.

        Runs in a background task (scheduled by the router) so the webhook can
        return 200 immediately. Idempotency guards against provider retries.
        """
        claimed = await self._dedup.claim(message.message_id)
        if not claimed:
            logger.info("wa_inbound_duplicate", extra={"message_id": message.message_id})
            return

        logger.info(
            "wa_inbound",
            extra={
                "message_id": message.message_id,
                "type": message.type,
                # wa_id is a phone number (PII) — log a coarse marker, not the value.
                "has_text": bool(message.text),
            },
        )

        # Emit analytics event for message received (Phase A9 / BR-050).
        await self._analytics.emit(
            AnalyticsEventType.MESSAGE_RECEIVED,
            wa_id=message.wa_id,
            props={"type": message.type},
        )

        # Advance conversation state (Phase A3). When no manager is wired (e.g.
        # minimal tests) we fall back to the stateless echo behavior.
        session: Session | None = None
        is_new_conversation = False
        if self._conversations is not None:
            session = await self._conversations.record_inbound(
                message.wa_id, message.text, name=message.name
            )
            # Emit conversation_started if this is the first message in a new session.
            if session.context.extra.get("_first_message"):
                is_new_conversation = True
                session.context.extra["_first_message"] = False
                await self._analytics.emit(
                    AnalyticsEventType.CONVERSATION_STARTED,
                    wa_id=message.wa_id,
                )

        reply = await self.build_reply(message, session)
        if reply is not None:
            await self._sender.send(reply)
            if self._conversations is not None and session is not None and reply.text:
                await self._conversations.record_agent_reply(session, reply.text)

    async def build_reply(
        self, message: InboundMessage, session: Session | None = None
    ) -> OutboundMessage | None:
        """Produce a reply for an inbound message.

        Order of precedence:
        1. Auto-reply disabled → stay silent.
        2. Human handover → one-time acknowledgement, then stay silent (BR-003).
        3. Prompt-injection attempt → refuse in-place, never call the model (BR-044).
        4. LLM orchestrator wired → model + tool-calling reply (Phase A4).
        5. Conversation manager wired → state-aware placeholder (Phase A3).
        6. Nothing wired → legacy stateless echo (Phase A2).
        """
        if not self._settings.wa_echo_reply:
            return None

        to = message.to_reply()

        # A human has taken over (BR-003 / Phase A8). Send a single friendly
        # acknowledgement the first time, then go quiet so we don't talk over
        # the human. The ack copy matches the reason that triggered handover.
        if session is not None and session.handover:
            return self._handover_reply(to, session)

        # Prompt-injection / extraction attempt: refuse before the model ever
        # sees it, so no crafted input can reach the LLM's tools or coax out
        # internals (BR-044 / Phase A8). Does not escalate to a human by itself.
        if is_injection_attempt(message.text):
            logger.warning("prompt_injection_blocked")
            await self._analytics.emit(
                AnalyticsEventType.INJECTION_BLOCKED,
                wa_id=message.wa_id if message else None,
            )
            return OutboundMessage.text_message(to, REFUSAL_REPLY)

        # Phase A4: let the orchestrator generate the reply from the session
        # context + tools. It never raises (degrades to a safe apology).
        if self._orchestrator is not None and session is not None:
            text = await self._orchestrator.reply(session, message.text)
            return OutboundMessage.text_message(to, text)

        if session is not None:
            return OutboundMessage.text_message(to, _reply_for_state(session, message.text))

        # No conversation manager wired: legacy stateless echo.
        if message.text:
            return OutboundMessage.text_message(to, f"Echo: {message.text}")
        return OutboundMessage.text_message(to, "Halo! Pesan kamu sudah kami terima.")

    def _handover_reply(self, to: str, session: Session) -> OutboundMessage | None:
        """One-time handover acknowledgement; silent on later messages.

        The first message after a session enters handover gets a warm ack keyed
        to the trigger reason (so the customer knows a human is coming). We mark
        the session so subsequent messages stay silent — the human is handling
        it now and the bot shouldn't talk over them (BR-003).
        """
        if session.context.extra.get(_HANDOVER_ACKED_KEY):
            return None
        session.context.extra[_HANDOVER_ACKED_KEY] = True
        reason_value = session.context.extra.get(HANDOVER_REASON_KEY)
        try:
            reason = (
                HandoverReason(reason_value)
                if reason_value
                else HandoverReason.CUSTOMER_REQUEST
            )
        except ValueError:
            reason = HandoverReason.CUSTOMER_REQUEST
        return OutboundMessage.text_message(to, acknowledgement(reason))




# Phase A3 placeholder copy per stage. Retained as the fallback when no LLM
# orchestrator is wired (e.g. tests, or LLM disabled). Intentionally free of
# prices/stock/totals (those come from the backend via tools in Phase A4+).
_STATE_REPLIES: dict[ConversationState, str] = {
    ConversationState.GREETING: "Halo! Ada yang bisa kami bantu hari ini?",
    ConversationState.DISCOVERY: "Boleh cerita produk seperti apa yang kamu cari?",
    ConversationState.PRODUCT: "Oke, aku bantu cek produknya ya.",
    ConversationState.CART: "Siap, aku catat ke keranjang kamu.",
    ConversationState.CUSTOMER_INFO: "Boleh dibantu data pengirimannya?",
    ConversationState.SHIPPING: "Baik, aku bantu cek opsi pengiriman.",
    ConversationState.CHECKOUT_CONFIRM: "Sebelum lanjut, aku ringkas dulu pesanannya ya.",
    ConversationState.PAYMENT: "Oke, aku siapkan info pembayarannya.",
    ConversationState.POST_PAYMENT: "Terima kasih! Pesanan kamu sedang kami proses.",
    ConversationState.DONE: "Terima kasih sudah berbelanja!",
}


def _reply_for_state(session: Session, text: str | None) -> str:
    """Pick a state-appropriate acknowledgement, personalized when possible."""
    base = _STATE_REPLIES.get(session.state, "Pesan kamu sudah kami terima.")
    name = session.context.name
    if name and session.state in (ConversationState.GREETING, ConversationState.DISCOVERY):
        return f"Halo {name}! {base}"
    return base
